<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es">
<context>
    <name>CheckConnectGUIRunner</name>
    <message>
        <location filename="../gui_main.py" line="139"/>
        <source>CheckConnect GUI - Version </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="166"/>
        <source>Test NTP</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="168"/>
        <source>Test URLs</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="170"/>
        <source>Generate Report</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="172"/>
        <source>Show summary</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="179"/>
        <source>Exit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="208"/>
        <source>Results and logs will appear here…</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="219"/>
        <source>Running NTP tests…</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="228"/>
        <source>NTP test failed: {e}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="230"/>
        <source>NTP tests completed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="240"/>
        <source>Running URL tests…</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="249"/>
        <source>URL test failed: {e}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="251"/>
        <source>URL tests completed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="276"/>
        <source>Failed to generate reports: {e}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="278"/>
        <source>Reports generated successfully.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="318"/>
        <source>HTML summary generated</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="321"/>
        <source>Text summary generated</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="324"/>
        <source>Failed to generate summary: {e}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui_main.py" line="337"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
